id: JoeSecurityTestPlaybook
version: -1
name: JoeSecurityTestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1a2344b9-8eec-4d74-8321-86ea155061e3
    type: start
    task:
      id: 1a2344b9-8eec-4d74-8321-86ea155061e3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: a22304d1-1b67-49bd-8228-30164e914e18
    type: regular
    task:
      id: a22304d1-1b67-49bd-8228-30164e914e18
      version: -1
      name: Start fresh
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 122e393c-1a86-456d-832c-62b6d6df04a8
    type: regular
    task:
      id: 122e393c-1a86-456d-832c-62b6d6df04a8
      version: -1
      name: Validate instance is working
      script: '|||joe-is-online'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 01075964-efb4-4e8b-883a-9ebe80f18019
    type: regular
    task:
      id: 01075964-efb4-4e8b-883a-9ebe80f18019
      version: -1
      name: Analyse a file using a url without waiting
      script: Joe Security|||joe-analysis-submit-sample
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      comments: {}
      file_id: {}
      internet-access: {}
      sample_url:
        simple: http://www.tutorialspoint.com/java/java_tutorial.pdf
      should_wait: {}
      systems: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: eaf6b493-8999-4e0f-8911-655b7171c191
    type: regular
    task:
      id: eaf6b493-8999-4e0f-8911-655b7171c191
      version: -1
      name: Analyse a url without waiting
      script: Joe Security|||joe-analysis-submit-url
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      comments: {}
      internet-access: {}
      should_wait:
        simple: "False"
      systems: {}
      url:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 8c329d46-2871-45c5-8f58-abbf3e109d9f
    type: regular
    task:
      id: 8c329d46-2871-45c5-8f58-abbf3e109d9f
      version: -1
      name: Get info on the file analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[1].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: c5268527-57eb-4b2f-8299-15a0877cc78c
    type: regular
    task:
      id: c5268527-57eb-4b2f-8299-15a0877cc78c
      version: -1
      name: Get info on the URL analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[2].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: e521c99c-6637-4dce-868a-e50f9f554327
    type: regular
    task:
      id: e521c99c-6637-4dce-868a-e50f9f554327
      version: -1
      name: Create sample file
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      data:
        simple: qwerty
      entryId: {}
      filename:
        simple: zaq.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1745
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: c6d7fe75-51b2-4a15-8ed7-75571736c09c
    type: regular
    task:
      id: c6d7fe75-51b2-4a15-8ed7-75571736c09c
      version: -1
      name: Search command
      script: Joe Security|||joe-search
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "14"
      - "16"
      - "17"
    scriptarguments:
      query:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 3b34310d-2f40-4632-8c0a-e4e85ca3fe62
    type: regular
    task:
      id: 3b34310d-2f40-4632-8c0a-e4e85ca3fe62
      version: -1
      name: Download url Report - XML
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      type:
        simple: xml
      webid:
        simple: ${Joe.Analysis(val.Status == "finished").[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: b9744543-1206-40eb-8bd3-6e155922266b
    type: regular
    task:
      id: b9744543-1206-40eb-8bd3-6e155922266b
      version: -1
      name: Download url Report - JSON
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: json
      webid:
        simple: ${Joe.Analysis(val.Status == "finished").[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 950,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 6fd8d1d0-5a76-4869-8a9b-b5f4b6653b56
    type: regular
    task:
      id: 6fd8d1d0-5a76-4869-8a9b-b5f4b6653b56
      version: -1
      name: Download url Report - HTML
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: html
      webid:
        simple: ${Joe.Analysis(val.Status == "finished").[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: e47c4860-7a47-4c37-802b-71eff53c9927
    type: condition
    task:
      id: e47c4860-7a47-4c37-802b-71eff53c9927
      version: -1
      name: verify output DBotScore.Indicator
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: DBotScore.Indicator
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1790,
        "width": 1280,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
