id: JoeSecurityTestPlaybook
version: -1
name: JoeSecurityTestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: fe8a38ba-3678-49b8-864e-0af5ce802f7b
    type: start
    task:
      id: fe8a38ba-3678-49b8-864e-0af5ce802f7b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: e1ecf1c9-8c05-4667-8587-eac5f85497d8
    type: regular
    task:
      id: e1ecf1c9-8c05-4667-8587-eac5f85497d8
      version: -1
      name: Start fresh
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 6aead7b3-fba8-47ca-8d50-997ac6bb6672
    type: regular
    task:
      id: 6aead7b3-fba8-47ca-8d50-997ac6bb6672
      version: -1
      name: Validate instance is working
      script: '|||joe-is-online'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: be011ce9-674c-4c6f-8900-564664d0d127
    type: regular
    task:
      id: be011ce9-674c-4c6f-8900-564664d0d127
      version: -1
      name: Analyse a file using a url without waiting
      script: Joe Security|||joe-analysis-submit-sample
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      comments: {}
      file_id: {}
      internet-access: {}
      sample_url:
        simple: http://www.tutorialspoint.com/java/java_tutorial.pdf
      should_wait: {}
      systems: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 99cbc529-27bb-4aa9-882e-020e2603ea90
    type: regular
    task:
      id: 99cbc529-27bb-4aa9-882e-020e2603ea90
      version: -1
      name: Analyse a url without waiting
      script: Joe Security|||joe-analysis-submit-url
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      comments: {}
      internet-access: {}
      should_wait:
        simple: "False"
      systems: {}
      url:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 3472de9c-d647-45ae-8885-0d6d7b7cecfe
    type: regular
    task:
      id: 3472de9c-d647-45ae-8885-0d6d7b7cecfe
      version: -1
      name: Get info on the file analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[1].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 8d866797-8702-4561-813b-2e403dba09ce
    type: regular
    task:
      id: 8d866797-8702-4561-813b-2e403dba09ce
      version: -1
      name: Get info on the URL analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[2].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 11590e15-e28b-4ddb-837e-c81f5b5bb53e
    type: regular
    task:
      id: 11590e15-e28b-4ddb-837e-c81f5b5bb53e
      version: -1
      name: Create sample file
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      data:
        simple: qwerty
      entryId: {}
      filename:
        simple: zaq.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1745
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 2153bad8-4010-4a43-81ea-d6d7279d3c02
    type: regular
    task:
      id: 2153bad8-4010-4a43-81ea-d6d7279d3c02
      version: -1
      name: Search command
      script: Joe Security|||joe-search
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "14"
      - "16"
      - "17"
    scriptarguments:
      query:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 8a5b01ab-7813-426e-8492-f4b216db8061
    type: regular
    task:
      id: 8a5b01ab-7813-426e-8492-f4b216db8061
      version: -1
      name: Download url Report - XML
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      type:
        simple: xml
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 435f3653-ca9f-40bb-8ac8-0c40f57762fb
    type: regular
    task:
      id: 435f3653-ca9f-40bb-8ac8-0c40f57762fb
      version: -1
      name: Download url Report - JSON
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: json
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 950,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: becbcc89-df44-4c49-8be9-56466e129712
    type: regular
    task:
      id: becbcc89-df44-4c49-8be9-56466e129712
      version: -1
      name: Download url Report - HTML
      script: Joe Security|||joe-download-report
      type: regular
      iscommand: true
      brand: Joe Security
    scriptarguments:
      type:
        simple: html
      webid:
        simple: ${Joe.Analysis.[0].WebID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 0b0c629c-fa31-4320-8a05-491d047abc0c
    type: condition
    task:
      id: 0b0c629c-fa31-4320-8a05-491d047abc0c
      version: -1
      name: verify output DBotScore.Indicator
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: DBotScore.Indicator
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1790,
        "width": 1280,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
